### ISSUE TITLE
wrongly categorized

### ISSUE THREAD

**Issue by monsieurpooh** [affige/genmusic_demo_list#1]
PerformanceRNN and GrooVAE are in the wrong categories; they generate MIDI; they do not generate audio given some midi or score

**Comment by monsieurpooh** [comment]
also can't find anything about generating audio in the GGNN link

**Comment by monsieurpooh** [comment]
VirtuosoNet is not generating audio either; it's generating human-like MIDI

**Comment by affige** [comment]
Thanks for pointing out the mistakes; I've corrected them.  I can't find the GGNN link either

**Comment by monsieurpooh** [comment]
Thanks very much for the changes; however it's worth noting that Magenta's Wave2Midi2Wave can still belong in the category of generating audio from MIDI (piano-only)
