### ISSUE TITLE
[SUGGESTION] Add Applio (Voice Cloning Software)

### ISSUE THREAD

**Issue by blaisewf** [affige/genmusic_demo_list#10]
I would like to add my Applio tool, in which category would it fit best? It has TTS and RVC based voice cloning.

https://github.com/IAHispano/Applio

**Comment by affige** [comment]
Thanks for the suggestion.  Although the repo is mainly for music related models, I've created a new category named "speech voice conversion / voice cloning" and put Applio there.  Thanks for making the tool available.
