### ISSUE TITLE
Thank you for the list

### ISSUE THREAD

**Issue by asigalov61** [affige/genmusic_demo_list#2]
Hey Yi-Hsuan,

Thank you so much for this amazing list and for keeping it current. Much appreciated and needed stuff :)

I wanted to ask you if you like to add my Jupyter Notebooks to the list (if you want).

Here are three of my repos specifically for easy exploration and research of Music AI :)

https://github.com/asigalov61/SuperPiano

https://github.com/asigalov61/Amazon-Deep-Composer

https://github.com/asigalov61/Noobiano

If you think this is useful, please add them as people looking for colabs as well.

Thank you.

**Comment by affige** [comment]
Hi thanks for the pointers!  Great to see your work!  However, my list is mainly for demo websites that accompany academic papers.   For consistency I would opt for leaving your links here.  Sorry about that!

**Comment by asigalov61** [comment]
Its ok. I do not mind. Thank you again for the list. Very useful :)
