### ISSUE TITLE
About open source code

### ISSUE THREAD

**Issue by Weiyinyin11** [affige/genmusic_demo_list#3]
Dear Professor, I recently read your paper "Fast Tensor Factorization for Large-scale Context-Aware Recommendation from Implicit Feedback".According to the article, the code of DropTF will be open source after the acceptance of the paper. May I ask, will the code of this paper be open source?If open source, how do you get it?

**Comment by affige** [comment]
Ooops we need to double check this with the first author of the paper; please write me a mail instead.
