### ISSUE TITLE
Some other Work to include (BasisMixer, SCHmUBERT)

### ISSUE THREAD

**Issue by manoskary** [affige/genmusic_demo_list#7]
Very nice curated list of nice work.
If I may propose some notable works that could be included in your list.

Under the `given MIDI, generate human-like MIDI: Piano only`:
[BasisMixer](https://wp.nyu.edu/ismir2016/wp-content/uploads/sites/2294/2016/08/cancino-basis.pdf) (RNN and FFNN) [https://www.youtube.com/watch?v=zdU8C6Su3TI](https://www.youtube.com/watch?v=zdU8C6Su3TI)

Under `Symbolic Generation`:
[SCHmUBERT ](https://arxiv.org/abs/2305.09489) (Discrete Diffusion Probabilistic Model) [Github Repo](https://github.com/plassma/symbolic-music-discrete-diffusion)

Thank you in advance.

**Comment by affige** [comment]
Added; many thanks for the pointer.
